# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fizzbuzz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fizzbuzz.Generator')),
            ],
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_to_append', models.IntegerField()),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fizzbuzz.Generator')),
            ],
        ),
    ]
