# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fizzbuzz', '0003_generator_results_per_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='hash_for_url',
            field=models.CharField(blank=True, help_text='This field will be generated automatically when saving the Generator', max_length=10),
        ),
    ]
