# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fizzbuzz', '0004_generator_hash_for_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='string',
            name='string_to_append',
            field=models.CharField(max_length=10),
        ),
    ]
