# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fizzbuzz', '0006_auto_20180313_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='hash_for_url',
            field=models.CharField(blank=True, help_text='This field will be generated automatically when saving the Generator. The URL will be: http://localhost:8000/generator/HASH', max_length=10),
        ),
    ]
